version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-all-{{ checksum "package-lock.json" }}
            - v1-deps-all-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-all-{{ checksum "package-lock.json" }}
      - run:
          name: Run Unit Tests
          command: npm test
